gt_path: "/data1/chenlong/online_model_set/video/eR6CMmTu_2/video_split/smooth"
latent_path: "/data1/chenlong/0517/video/0822/eR6CMmTu_2/eR6CMmTu_2_exp_set_v4_depoly/exp/facial"
pti:
    net:
        base_filter_num: 64
        source_size: 64
        target_size: 4
        target_filter_num: 512

    losses:
            - 
              alias: l2
              name: L2Loss
              weights: 1
            - 
              alias: lpips
              name: LPIPS
              weights: 1
            - 
              alias: l2_code
              name: L2Loss
              weights: 10
epochs: 50
batchsize: 4
lr: 0.5
resolution: 512
